/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTable: typeof import('./resources/js/components/AppTable.vue')['default']
    AppTableActions: typeof import('./resources/js/components/AppTableActions.vue')['default']
    CardStatements: typeof import('./resources/js/components/CardStatements.vue')['default']
    CreateBtn: typeof import('./resources/js/components/CreateBtn.vue')['default']
    DeleteDialog: typeof import('./resources/js/components/DeleteDialog.vue')['default']
    DueDateDialog: typeof import('./resources/js/components/DueDateDialog.vue')['default']
    FormAccount: typeof import('./resources/js/components/Form/FormAccount.vue')['default']
    FormCategory: typeof import('./resources/js/components/Form/FormCategory.vue')['default']
    FormDialog: typeof import('./resources/js/components/Form/FormDialog.vue')['default']
    FormTransaction: typeof import('./resources/js/components/Form/FormTransaction.vue')['default']
    SettleDialog: typeof import('./resources/js/components/SettleDialog.vue')['default']
    TransactionFilters: typeof import('./resources/js/components/TransactionFilters.vue')['default']
  }
}
