/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMenu: typeof import('./resources/js/components/AddMenu.vue')['default']
    AppLogo: typeof import('./resources/js/components/AppLogo.vue')['default']
    AppTable: typeof import('./resources/js/components/AppTable.vue')['default']
    AppTableActions: typeof import('./resources/js/components/AppTableActions.vue')['default']
    CardStatements: typeof import('./resources/js/components/CardStatements.vue')['default']
    CashFlowChart: typeof import('./resources/js/components/CashFlowChart.vue')['default']
    CreateBtn: typeof import('./resources/js/components/CreateBtn.vue')['default']
    DeleteDialog: typeof import('./resources/js/components/DeleteDialog.vue')['default']
    DividendMonths: typeof import('./resources/js/components/DividendMonths.vue')['default']
    DueDateDialog: typeof import('./resources/js/components/DueDateDialog.vue')['default']
    FlowPeriodControl: typeof import('./resources/js/components/Flow/PeriodControl.vue')['default']
    ForecastChart: typeof import('./resources/js/components/ForecastChart.vue')['default']
    ForecastMonths: typeof import('./resources/js/components/ForecastMonths.vue')['default']
    FormAccount: typeof import('./resources/js/components/Form/FormAccount.vue')['default']
    FormCategory: typeof import('./resources/js/components/Form/FormCategory.vue')['default']
    FormContextHost: typeof import('./resources/js/components/FormContextHost.vue')['default']
    FormDialog: typeof import('./resources/js/components/Form/FormDialog.vue')['default']
    FormRecurring: typeof import('./resources/js/components/Form/FormRecurring.vue')['default']
    FormTransaction: typeof import('./resources/js/components/Form/FormTransaction.vue')['default']
    HomeMonths: typeof import('./resources/js/components/HomeMonths.vue')['default']
    HomeSpark: typeof import('./resources/js/components/HomeSpark.vue')['default']
    NetWorthChart: typeof import('./resources/js/components/NetWorthChart.vue')['default']
    PeekDialog: typeof import('./resources/js/components/PeekDialog.vue')['default']
    PositionAllocation: typeof import('./resources/js/components/PositionAllocation.vue')['default']
    RecurringFindDialog: typeof import('./resources/js/components/RecurringFindDialog.vue')['default']
    SettleDialog: typeof import('./resources/js/components/SettleDialog.vue')['default']
    SignOutBtn: typeof import('./resources/js/components/SignOutBtn.vue')['default']
    TransactionFilters: typeof import('./resources/js/components/TransactionFilters.vue')['default']
    TransferDialog: typeof import('./resources/js/components/TransferDialog.vue')['default']
  }
}
